[project]
name = "auto-nethack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "autogen>=0.9",
    "autogenstudio>=0.4.2.1",
    "fastapi>=0.115.12",
    "minihack>=1.0.2",
    "nle>=1.1.0",
    "openai>=1.76.0",
    "uvicorn>=0.34.2",
    "websockets>=15.0.1",
]
